import type { PrimusTick } from '../../types/api'
import type { Exchange } from '../../types/domain'
import type { CandleEngine } from './candleEngine'
import type { MockClock } from './clock'
import { deriveSeed, mulberry32, pick, randomFloat, randomInt, type Rng } from './rng'

export type PrimusSocketState = 'connecting' | 'connected' | 'disconnected'

type TickListener = (tick: PrimusTick) => void
type StateListener = (state: PrimusSocketState) => void

interface Subscription {
  tokens: Set<string>
  listener: TickListener
}

/**
 * A mock stand-in for the (UNCONFIRMED, STRATEGY-CONTRACT.md §3.4) Primus
 * WebSocket feed. Same lifecycle shape as a real socket: connecting ->
 * connected, a heartbeat, a random disconnect roughly every 3-5 minutes
 * with exponential-backoff reconnect, and tokens staying subscribed across
 * a reconnect (a real client would need to resend a subscribe frame; here
 * the subscription set simply survives the reconnect and ticks resume for
 * the same tokens once back online). Every tick is generated by
 * CandleEngine.advanceLiveTick(), so a tick and the candle it belongs to
 * can never disagree.
 */
export class MockPrimusSocket {
  private state: PrimusSocketState = 'disconnected'
  private readonly subscriptions = new Set<Subscription>()
  private readonly stateListeners = new Set<StateListener>()
  private readonly rng: Rng
  private readonly clock: MockClock
  private readonly getCandleEngine: () => CandleEngine
  private readonly getStartPrice: (token: string) => number
  private readonly getExchange: (token: string) => Exchange

  private heartbeatTimer: ReturnType<typeof setInterval> | null = null
  private tickTimer: ReturnType<typeof setTimeout> | null = null
  private disconnectTimer: ReturnType<typeof setTimeout> | null = null
  private connectTimer: ReturnType<typeof setTimeout> | null = null
  private reconnectAttempt = 0
  private ticksPerSecond = 2
  private destroyed = false

  constructor(
    clock: MockClock,
    getCandleEngine: () => CandleEngine,
    getStartPrice: (token: string) => number,
    getExchange: (token: string) => Exchange,
    seed: number,
  ) {
    this.clock = clock
    this.getCandleEngine = getCandleEngine
    this.getStartPrice = getStartPrice
    this.getExchange = getExchange
    this.rng = mulberry32(deriveSeed(seed, 'primus'))
    this.beginConnect()
  }

  getState(): PrimusSocketState {
    return this.state
  }

  onStateChange(listener: StateListener): () => void {
    this.stateListeners.add(listener)
    return () => this.stateListeners.delete(listener)
  }

  subscribe(tokens: string[], listener: TickListener): () => void {
    const subscription: Subscription = { tokens: new Set(tokens), listener }
    this.subscriptions.add(subscription)
    return () => {
      this.subscriptions.delete(subscription)
    }
  }

  /** Devtools hook: force a disconnect right now, still followed by the normal backoff reconnect. */
  forceDisconnect(): void {
    if (this.state === 'disconnected') return
    this.handleDisconnect()
  }

  destroy(): void {
    this.destroyed = true
    this.clearTimers()
  }

  private setState(state: PrimusSocketState): void {
    this.state = state
    this.stateListeners.forEach((listener) => listener(state))
  }

  private clearTimers(): void {
    if (this.heartbeatTimer) clearInterval(this.heartbeatTimer)
    if (this.tickTimer) clearTimeout(this.tickTimer)
    if (this.disconnectTimer) clearTimeout(this.disconnectTimer)
    if (this.connectTimer) clearTimeout(this.connectTimer)
    this.heartbeatTimer = null
    this.tickTimer = null
    this.disconnectTimer = null
    this.connectTimer = null
  }

  private beginConnect(): void {
    this.setState('connecting')
    const delay = randomInt(this.rng, 150, 600)
    this.connectTimer = setTimeout(() => this.finishConnect(), delay)
  }

  private finishConnect(): void {
    if (this.destroyed) return
    this.setState('connected')
    this.reconnectAttempt = 0
    this.ticksPerSecond = randomFloat(this.rng, 1, 4)
    this.scheduleHeartbeat()
    this.scheduleRandomDisconnect()
    this.scheduleTick()
  }

  private scheduleHeartbeat(): void {
    // Presence of a periodic heartbeat is the point here, not its payload —
    // a real client would ping/pong to detect a dead connection.
    this.heartbeatTimer = setInterval(() => {}, 15000)
  }

  private scheduleRandomDisconnect(): void {
    const delay = randomInt(this.rng, 3 * 60 * 1000, 5 * 60 * 1000)
    this.disconnectTimer = setTimeout(() => this.handleDisconnect(), delay)
  }

  private handleDisconnect(): void {
    if (this.destroyed) return
    this.clearTimers()
    this.setState('disconnected')
    this.reconnectAttempt += 1
    const backoff = Math.min(30000, 500 * 2 ** this.reconnectAttempt)
    this.connectTimer = setTimeout(() => this.reconnect(), backoff)
  }

  private reconnect(): void {
    if (this.destroyed) return
    this.setState('connecting')
    const delay = randomInt(this.rng, 150, 600)
    this.connectTimer = setTimeout(() => this.finishConnect(), delay)
  }

  private scheduleTick(): void {
    if (this.destroyed || this.state !== 'connected') return
    const delay = 1000 / this.ticksPerSecond
    this.tickTimer = setTimeout(() => {
      this.emitTick()
      this.scheduleTick()
    }, delay)
  }

  private allSubscribedTokens(): string[] {
    const tokens = new Set<string>()
    this.subscriptions.forEach((sub) => sub.tokens.forEach((token) => tokens.add(token)))
    return Array.from(tokens)
  }

  private emitTick(): void {
    const tokens = this.allSubscribedTokens()
    if (tokens.length === 0) return

    const token = pick(this.rng, tokens)
    const now = this.clock.now()
    const { price, candle } = this.getCandleEngine().advanceLiveTick(token, this.getStartPrice(token), now)

    const tick: PrimusTick = {
      token,
      exchange: this.getExchange(token),
      ltp: price,
      ltt: now,
      volume: candle.volume,
      o: candle.open,
      h: candle.high,
      l: candle.low,
      c: candle.close,
    }

    this.subscriptions.forEach((sub) => {
      if (sub.tokens.has(token)) sub.listener(tick)
    })
  }
}
