import type { PrimusTick } from '../../types/api'
import type { Exchange } from '../../types/domain'
import type { CandleEngine } from './candleEngine'
import type { MockClock } from './clock'
import { deriveSeed, mulberry32, randomFloat, randomInt, type Rng } from './rng'

export type PrimusSocketState = 'connecting' | 'connected' | 'disconnected'

type TickListener = (tick: PrimusTick) => void
type StateListener = (state: PrimusSocketState) => void

interface Subscription {
  tokens: Set<string>
  listener: TickListener
  /** Tokens this subscriber currently has on screen — biases batch selection, never excludes. */
  priority: Set<string>
}

export interface SubscribeOptions {
  priority?: string[]
}

/**
 * The socket ticks at this fixed cadence regardless of how many tokens are
 * subscribed — one shared timer serving the whole universe (200+ F&O
 * tokens) rather than a per-token timer, which is what "batching" buys: a
 * bounded number of JS scheduling events per second no matter how large the
 * universe gets.
 */
const BATCHES_PER_SECOND = 10
const BATCH_INTERVAL_MS = 1000 / BATCHES_PER_SECOND
/** How many non-priority tokens get folded into each batch, on top of every priority token. */
const NON_PRIORITY_TOKENS_PER_BATCH = 10

/**
 * A mock stand-in for the (UNCONFIRMED, STRATEGY-CONTRACT.md §3.4) Primus
 * WebSocket feed. Same lifecycle shape as a real socket: connecting ->
 * connected, a heartbeat, a random disconnect roughly every 3-5 minutes
 * with exponential-backoff reconnect, and tokens staying subscribed across
 * a reconnect (a real client would need to resend a subscribe frame; here
 * the subscription set simply survives the reconnect and ticks resume for
 * the same tokens once back online). Every tick is generated by
 * CandleEngine.advanceLiveTick(), so a tick and the candle it belongs to
 * can never disagree. Silent outside market hours, like the real feed.
 */
export class MockPrimusSocket {
  private state: PrimusSocketState = 'disconnected'
  private readonly subscriptions = new Set<Subscription>()
  private readonly stateListeners = new Set<StateListener>()
  private readonly rng: Rng
  private readonly clock: MockClock
  private readonly getCandleEngine: () => CandleEngine
  private readonly getStartPrice: (token: string) => number
  private readonly getExchange: (token: string) => Exchange

  private heartbeatTimer: ReturnType<typeof setInterval> | null = null
  private tickTimer: ReturnType<typeof setTimeout> | null = null
  private disconnectTimer: ReturnType<typeof setTimeout> | null = null
  private connectTimer: ReturnType<typeof setTimeout> | null = null
  private reconnectAttempt = 0
  /** Persists across batches so round-robin coverage of non-priority tokens actually advances instead of restarting each time. */
  private nonPriorityCursor = 0
  private destroyed = false

  constructor(
    clock: MockClock,
    getCandleEngine: () => CandleEngine,
    getStartPrice: (token: string) => number,
    getExchange: (token: string) => Exchange,
    seed: number,
  ) {
    this.clock = clock
    this.getCandleEngine = getCandleEngine
    this.getStartPrice = getStartPrice
    this.getExchange = getExchange
    this.rng = mulberry32(deriveSeed(seed, 'primus'))
    this.beginConnect()
  }

  getState(): PrimusSocketState {
    return this.state
  }

  onStateChange(listener: StateListener): () => void {
    this.stateListeners.add(listener)
    return () => this.stateListeners.delete(listener)
  }

  subscribe(tokens: string[], listener: TickListener, opts?: SubscribeOptions): () => void {
    const subscription: Subscription = { tokens: new Set(tokens), listener, priority: new Set(opts?.priority ?? []) }
    this.subscriptions.add(subscription)
    return () => {
      this.subscriptions.delete(subscription)
    }
  }

  /** Devtools hook: force a disconnect right now, still followed by the normal backoff reconnect. */
  forceDisconnect(): void {
    if (this.state === 'disconnected') return
    this.handleDisconnect()
  }

  destroy(): void {
    this.destroyed = true
    this.clearTimers()
  }

  private setState(state: PrimusSocketState): void {
    this.state = state
    this.stateListeners.forEach((listener) => listener(state))
  }

  private clearTimers(): void {
    if (this.heartbeatTimer) clearInterval(this.heartbeatTimer)
    if (this.tickTimer) clearTimeout(this.tickTimer)
    if (this.disconnectTimer) clearTimeout(this.disconnectTimer)
    if (this.connectTimer) clearTimeout(this.connectTimer)
    this.heartbeatTimer = null
    this.tickTimer = null
    this.disconnectTimer = null
    this.connectTimer = null
  }

  private beginConnect(): void {
    this.setState('connecting')
    const delay = randomInt(this.rng, 150, 600)
    this.connectTimer = setTimeout(() => this.finishConnect(), delay)
  }

  private finishConnect(): void {
    if (this.destroyed) return
    this.setState('connected')
    this.reconnectAttempt = 0
    this.scheduleHeartbeat()
    this.scheduleRandomDisconnect()
    this.scheduleBatch()
  }

  private scheduleHeartbeat(): void {
    // Presence of a periodic heartbeat is the point here, not its payload —
    // a real client would ping/pong to detect a dead connection.
    this.heartbeatTimer = setInterval(() => {}, 15000)
  }

  private scheduleRandomDisconnect(): void {
    const delay = randomInt(this.rng, 3 * 60 * 1000, 5 * 60 * 1000)
    this.disconnectTimer = setTimeout(() => this.handleDisconnect(), delay)
  }

  private handleDisconnect(): void {
    if (this.destroyed) return
    this.clearTimers()
    this.setState('disconnected')
    this.reconnectAttempt += 1
    const backoff = Math.min(30000, 500 * 2 ** this.reconnectAttempt)
    this.connectTimer = setTimeout(() => this.reconnect(), backoff)
  }

  private reconnect(): void {
    if (this.destroyed) return
    this.setState('connecting')
    const delay = randomInt(this.rng, 150, 600)
    this.connectTimer = setTimeout(() => this.finishConnect(), delay)
  }

  private scheduleBatch(): void {
    if (this.destroyed || this.state !== 'connected') return
    const jitter = randomFloat(this.rng, 0.85, 1.15)
    this.tickTimer = setTimeout(() => {
      this.emitBatch()
      this.scheduleBatch()
    }, BATCH_INTERVAL_MS * jitter)
  }

  private allSubscribedTokens(): string[] {
    const tokens = new Set<string>()
    this.subscriptions.forEach((sub) => sub.tokens.forEach((token) => tokens.add(token)))
    return Array.from(tokens)
  }

  private allPriorityTokens(subscribed: readonly string[]): Set<string> {
    const subscribedSet = new Set(subscribed)
    const priority = new Set<string>()
    this.subscriptions.forEach((sub) => sub.priority.forEach((token) => {
      if (subscribedSet.has(token)) priority.add(token)
    }))
    return priority
  }

  /**
   * Every priority token ticks every batch (so visible rows feel live);
   * NON_PRIORITY_TOKENS_PER_BATCH more come from the rest of the universe,
   * round-robin (nonPriorityCursor persists across batches) so a 200+ token
   * universe still cycles through fully over a few seconds instead of the
   * same handful of tokens ticking forever.
   */
  private selectBatchTokens(): string[] {
    const allTokens = this.allSubscribedTokens()
    if (allTokens.length === 0) return []

    const priority = this.allPriorityTokens(allTokens)
    const nonPriorityPool = allTokens.filter((token) => !priority.has(token))

    const selected = new Set<string>(priority)
    const take = Math.min(NON_PRIORITY_TOKENS_PER_BATCH, nonPriorityPool.length)
    for (let i = 0; i < take; i++) {
      selected.add(nonPriorityPool[this.nonPriorityCursor % nonPriorityPool.length])
      this.nonPriorityCursor += 1
    }

    return Array.from(selected)
  }

  private emitBatch(): void {
    // Outside market hours a real feed is silent — no ticks, so nothing on
    // screen moves and no bars are invented. The socket stays connected (a
    // real one would too); ticks resume on their own at the next open.
    // "Force OPEN" (devtools) is the explicit override for after-hours demos.
    const forced = this.clock.getState().forceSessionOpen
    if (!forced && this.clock.getMarketSession() !== 'OPEN') return

    const tokens = this.selectBatchTokens()
    if (tokens.length === 0) return

    const now = this.clock.now()
    for (const token of tokens) {
      const live = this.getCandleEngine().advanceLiveTick(token, this.getStartPrice(token), now, forced)
      if (!live) continue
      const { price, candle } = live

      const tick: PrimusTick = {
        token,
        exchange: this.getExchange(token),
        ltp: price,
        ltt: now,
        volume: candle.volume,
        o: candle.open,
        h: candle.high,
        l: candle.low,
        c: candle.close,
      }

      this.subscriptions.forEach((sub) => {
        if (sub.tokens.has(token)) sub.listener(tick)
      })
    }
  }
}
